### ISSUE TITLE
Add transform method

### ISSUE THREAD

**Issue by chris-greening** [chris-greening/spyrograph#109]
**Is your feature request related to a problem? Please describe.**
Add method that transforms object's origin left or right based on given user input

**Comment by SahilDave04** [comment]
Hey!
Can you give an example?

**Comment by SahilDave04** [comment]
I'll try doing it.

**Comment by chris-greening** [comment]
Ahh @SahilDave04 I'm so sorry I actually completed this yesterday with #111 and forgot to close the issue 😅 

I'm going to be opening a bunch more Issues in a few minutes though so please feel free to jump onto one of those :D

**Comment by chris-greening** [comment]
Completed with #111
