### ISSUE TITLE
Run pylint against _Cycloid and fix any issues

### ISSUE THREAD

**Issue by chris-greening** [chris-greening/spyrograph#114]
**Is your feature request related to a problem? Please describe.**
Run `pylint` against [_Cycloid](https://github.com/chris-greening/spyrograph/blob/main/spyrograph/_cycloid.py) and fix any of the issues that pylint flags. If there is anything that should be silenced then add inline disables where it makes sense

**Comment by Sjorza** [comment]
I would like to work on this

**Comment by chris-greening** [comment]
Go for it @Sjorza ! Honestly idr but earlier I was doing some work on `_Cycloid` which might've resolved any issues but if you could double check and open a PR if anything is tripping up that would be fantastic - thank you for your continued support on these :D

**Comment by Sjorza** [comment]
No problem. I'm happy to help. I will double check it. Do you want me to put inline disables if something shows up in Pylint?

**Comment by chris-greening** [comment]
Yeee so if it's something that can easily be resolved properly go for it as pylint wants (like breaking code up vertically if the line is too long, etc.) but if it's something that can't be cleanly resolved then go ahead and inline disable it (`_trochoid._Trochoid.plot` is a good example, there's a `raise ImportError` in there that has a long string that triggers line-too-long but it doesn't really make sense to break it into multiple lines so I just disabled it)

Thank you! :D

**Comment by chris-greening** [comment]
Fixed #126
