### ISSUE TITLE
Refactor the __repr__ for _Trochoid

### ISSUE THREAD

**Issue by chris-greening** [chris-greening/spyrograph#117]
**Is your feature request related to a problem? Please describe.**
We should refactor __repr__ in _trochoid._Trochoid to be cleaner 

Currently we have a chain of if-elif-else statements that check for how many elements of theta are in `thetas`. It works but its fairly ugly and I'm sure there is a more Pythonic solution that could be applied here

Basically `thetas` contains a list of user defined theta values such as [0, 0.1, 0.2, 0.3 ... 3.3, 3.4]. For the __repr__ display we only want to show the first element of the list, the second element (to show the increment of thetas], and the last element so that the list would display like `thetas=[0, 0.1, ... 3.4]`. 

The logic needs to be applied for if the list has 
- one element (i.e. [0])
- two elements (i.e. [0, 1])
- three elements (i.e. [0, 1, 2])
- n elements (i.e. [0, 1, ... 10])

**Comment by jlonge4** [comment]
@chris-greening Think this one is g2g

**Comment by chris-greening** [comment]
Fixed w #122
