### ISSUE TITLE
Add ability to draw animations of complete roulettes

### ISSUE THREAD

**Issue by chris-greening** [chris-greening/spyrograph#22]
**Is your feature request related to a problem? Please describe.**
Add ability to draw animations of spirographs changing as a function of input lengths i.e. we draw the full spirograph from 0 to 2pi but each frame of the animation would increment radius of the fixed circle, etc.

**Comment by UzairURK** [comment]
Hi,
@chris-greening 
I want to work on this issue. Can you assign this to me, So I can start working on this soon?

**Comment by chris-greening** [comment]
Hey @UzairURK - thanks so much for your interest in contributing! :D 

Goal here is to draw the trochoids or cycloids across varying input parameters like shown here:

![Image showing a circular outline changing as shape changes](https://res.cloudinary.com/practicaldev/image/fetch/s--vmpQ80b6--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_66%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/nq1gew5eiewu9zm3j913.gif)

Using the hypotrochoid for example we can define a single "frame of the animation" like so:
```python
from spyrograph import Hypotrochoid
import numpy as np

hypotrochoid = Hypotrochoid(
    R = 300,
    r = 200, 
    d = 100,
    thetas = np.arange(0, 2*np.pi, .1)
)

screen = hypotrochoid.trace()
````

To create an animation similar to the one I showed above we can increment one of the input radii (`R`, `r`) or distance (`d`) and create many hypotrochoids each with slightly different inputs. Upon linking the animation together of the complete drawing together we get a continuous animation like above (see the GIF below to understand what I mean: the animation is the total book and each "frame" is like a single piece of paper)

![GIF of candy corn with arms and legs being animated by a flipbook and dancing](https://media0.giphy.com/media/KWRG5ATZaiBOjCCjVO/200w.gif?cid=6c09b9522vnn0ydr3khqylaojohkajo56rc1mn0qyqjh9azq&rid=200w.gif&ct=g)

Something along the lines of:
```python
from spyrograph import Hypotrochoid
import numpy as np

hypotrochoids = [hypotrochoid(R=300, r=r, d=100, thetas=np.arange(0, 2*np.pi, .1) for r in range(200, 300)]
```

We'll have to think of a good way to integrate this into the library since one instance is "one frame". Perhaps a `classmethod` that takes similar inputs as an individual instance? 

Feel free to submit a draft PR so we can get an open dialogue going!

**Comment by UzairURK** [comment]
Great! I will keep updating you on my progress!

**Comment by UzairURK** [comment]
I have understood the above all. Even If I get stuck, I will ask you right away.

**Comment by UzairURK** [comment]
Hi,
@chris-greening,
can you just tell me where to start like which is the main file to run, although I have installed all libraries (requirments.txt)

**Comment by chris-greening** [comment]
VS Code is perfect!

This project is a [Python package](https://pypi.org/project/spyrograph/) so there isn't really a main entrypoint - users can import the package and use any of its features as needed. I'd recommend taking a look at the [Quickstart](https://github.com/chris-greening/spyrograph#quickstart) and the [docs](https://spyrograph.readthedocs.io/en/latest/source/spyrograph.hypotrochoid.html) to get an idea of how the library is used!

The user-facing API is essentially a collection of child classes that inherit from a [_Trochoid](https://github.com/chris-greening/spyrograph/blob/main/spyrograph/_trochoid.py) abstract base class that defines most of the [tracing](https://github.com/chris-greening/spyrograph/blob/main/spyrograph/_trochoid.py#L90), [plotting](https://github.com/chris-greening/spyrograph/blob/main/spyrograph/_trochoid.py#L76), etc. functionality so this is a good place to start as defining the animation method here will inherit down to the concrete implementations (i.e. [Hypotrochoid](https://github.com/chris-greening/spyrograph/blob/main/spyrograph/hypotrochoid/hypotrochoid.py), [Epitrochoid](https://github.com/chris-greening/spyrograph/blob/main/spyrograph/epitrochoid/epitrochoid.py), etc.) 

I think a good place to start would be to take a look at [_Roulette.trace](https://github.com/chris-greening/spyrograph/blob/main/spyrograph/_trochoid.py#L90) as this is the workhorse that does the `turtle` drawing. You can instantiate a `turtle.Screen` object, pass it to `_Roulette.trace` and it will draw on the `screen` and return the `turtle.Screen` object back. This allows you to pass the screen back and forth and draw new shapes on it iteratively

Try running this as some sample code to get an idea of what the animation will look like and how you can draw it:
```python
from spyrograph import Hypotrochoid
import numpy as np
import turtle

screen = None
for R in np.arange(200, 300, .5):
    hypotrochoid = Hypotrochoid(
        R=R,
        r=149,
        d=24,
        theta_start=0,
        theta_stop=10*np.pi,
        theta_step=.1,
    )
    screen = hypotrochoid.trace(screen=screen)
    screen.clear()
```

Right now the animation is gonna be pretty jittery because of how the frame updating works but that's okay! Just want to get some basic functionality in

I'm going to go open a PR with some sample code in so you know exactly where to get started! Will tag and assign you in it as soon as its ready. 

Thank you so much for your interest in contributing btw! :D

**Comment by chris-greening** [comment]
@UzairURK alrighty check out the latest commits over in #60, these should set you on the right path! 

I created a `create_range` classmethod that will create a list of objects over a given input parameter range - you can leverage this to create the objects, iterate over them like I showed above, then trace each individual shape

Let me know if that makes sense!

**Comment by UzairURK** [comment]
@chris-greening 
I was about to finish but you have done well.

**Comment by chris-greening** [comment]
@UzairURK how do you mean?

**Comment by chris-greening** [comment]
Aahhhh I accidentally closed the task... yeah the feature's not complete but no worries, apologies for the confusion

**Comment by UzairURK** [comment]
@chris-greening 
I got too confused because I have started working on it as It was assigned to me.
Should I resume working on it?

**Comment by chris-greening** [comment]
@UzairURK completely my fault, I didn't realize the Issue was linked to one of the sample branches I was working on and it closed it accidentally 

Please feel free to continue working on it, again very sorry about the confusion!

**Comment by UzairURK** [comment]
@chris-greening 
No Problem, resuming working on it.

**Comment by chris-greening** [comment]
Heyo @UzairURK! just checking in for a status update - how are things going with this?

**Comment by UzairURK** [comment]
I would open PR this weekend hopefully.

**Comment by chris-greening** [comment]
Heyo @UzairURK! :D 

No worries if not but do you think you'll get to it this weekend? If not no problem I'll reassign to myself, this is a key feature for the project I want to get moving on - would love to get you involved on a different issue if that would be easier!

**Comment by UzairURK** [comment]
@chris-greening,
Thanks! I have worked on it somehow, Now due to my mid-terms and semester projects, I decided to work on this after two weeks Now, I am really interested in this but If you want you can reassign it to yourself and I will work on another issue. How does it sound?

**Comment by chris-greening** [comment]
No worries at all! I was a university student myself not too long ago so I totally understand the struggle 😅 I'll reassign this one to myself but please feel free to hop onto a different issue - I'd love to get you in as a contributor!

I've flagged some low intensity ones such as #104 that might be easier with your schedule. Again thank you so much for your interest in contributing, always feel free to reach out 😄

**Comment by chris-greening** [comment]
Completed #108
