### ISSUE TITLE
Generalize Sphinx documentation further to remove need for hardcoding

### ISSUE THREAD

**Issue by chris-greening** [chris-greening/spyrograph#24]
**Is your feature request related to a problem? Please describe.**
I'm not fully familiar with Sphinx - I have api-doc setup and more or less "automated" but I have to manually add objects to the index.rst and specify :inherited-members: for each individual class. Ideally there's a way to automate this so index.rst automatically docs all available public objects and I can specify :inherited-members: as a default config that gets inherited (pun intended) across all "child" rst files 

Not sure what the possibility of this is but will investigate when I have some free time as this is noncritical and I can handle manually for now. Ideally I want doc generation to be completely automated as a part of the PyPI helper bash script I have so documentation is regenerated with each release

**Comment by markjacksonj** [comment]
assign me

**Comment by chris-greening** [comment]
Added `inherited-members` to `autodoc_default_options` in `conf.py` so this should trickle down now to all classes
