### ISSUE TITLE
Add repeating animation

### ISSUE THREAD

**Issue by chris-greening** [chris-greening/spyrograph#32]
**Is your feature request related to a problem? Please describe.**
Add a possible configuration to the tracing that repeats indefinitely

**Comment by sudheesanamp2003** [comment]
i will take it

**Comment by AiswaryaSgi** [comment]
i want it

**Comment by Aishu-5** [comment]
i need it

**Comment by manojkumar22092003** [comment]
i would like to work on it plz

**Comment by chris-greening** [comment]
A lot of bots are interacting with this project rn, if you can prove you aren't a bot respond to this message lol
