### ISSUE TITLE
Refactor objects into submodules

### ISSUE THREAD

**Issue by chris-greening** [chris-greening/spyrograph#33]
**Is your feature request related to a problem? Please describe.**
Currently everything is available as a toplevel import which is more or less okay but I think we can effectively group the hypotrochoid and its subclasses in a hypotrochoid submodule and the epitrochoid classes in a separate submodule

This would help mentally separate the different objects and know "okay these are organized with these"

**Comment by hariprasanth05** [comment]
i will take it
