### ISSUE TITLE
Add Quickstart section to homepage

### ISSUE THREAD

**Issue by chris-greening** [chris-greening/spyrograph#35]
**Is your feature request related to a problem? Please describe.**
Add installation and sample boilerplate for copying/pasting some of the core features of the project i.e. instantiating a hypotrochoid and tracing it

**Comment by DeenuRSD** [comment]
i will take this

**Comment by AkshayaVarshieni14** [comment]
i am ready to do this

**Comment by Aishu-5** [comment]
i need it

**Comment by markjacksonj** [comment]
assign me

**Comment by chris-greening** [comment]
A lot of bots are interacting with this project rn, if you can prove you aren't a bot respond to this message lol

**Comment by AkshayaVarshieni14** [comment]
I am not a bot

**Comment by chris-greening** [comment]
Hey @AkshayaVarshieni14 awesome! Thanks so much for your interest in the project :D 

I wrote a blog post for this project that has sample code for generating a simple trace - the sample code can be [found here](https://chris-greening.github.io/spyrograph/python/2023/03/11/draw-beautiful-geometric-visualizations-and-animations-with-python-and-spyrograph.html#using-spyrograph-for-effortless-modeling). 

Could you create a "Quickstart" section to this repo's [README](https://github.com/chris-greening/spyrograph/blob/main/README.md) as well as the gh-pages branch [home.md](https://github.com/chris-greening/spyrograph/blob/gh-pages/_pages/home.md) page that uses the aforementioned code snippet from that blog post? This will give users sample usage of the library to get them started

Again thank you so much for your interest! Please feel free to submit a PR with these changes 😄

**Comment by chris-greening** [comment]
Hey @AkshayaVarshieni14 !

I'm going to reassign this to myself, this is a quick task and I want to just knock this out fairly quickly 

Thanks so much for your interest - please let me know if you're still interested in contributing and we can definitely find more tasks for you to work on!

**Comment by AkshayaVarshieni14** [comment]
sorry i couldnt get back to you in time. Its fine. let me try some other time. thanks for assigning me for this task
