### ISSUE TITLE
Add requirements.txt

### ISSUE THREAD

**Issue by chris-greening** [chris-greening/spyrograph#36]
**Is your feature request related to a problem? Please describe.**
Add a requirements.txt file that defines what libraries are needed for the development environment i.e. pytest, pylint, matplotlib, pandas, etc.

**Comment by sudheesanamp2003** [comment]
i will take it

**Comment by Manojkumar192002** [comment]
i will do it

**Comment by Kowsalyasriganesh** [comment]
i will do it

**Comment by Manojkumar192002** [comment]
please assign me I'll do it

**Comment by Kowsalyasriganesh** [comment]
please assign me I'll do it

**Comment by Aishu-5** [comment]
i need it

**Comment by markjacksonj** [comment]
assign me

**Comment by dayanithi400** [comment]
I'll take this

**Comment by JJanany** [comment]
i will take this

**Comment by B-a-b-u** [comment]
I will take this

**Comment by chris-greening** [comment]
Solved with #44
