### ISSUE TITLE
Improve docstring for the `plot` method

### ISSUE THREAD

**Issue by chris-greening** [chris-greening/spyrograph#71]
**Is your feature request related to a problem? Please describe.**
Currently the [`plot`](https://github.com/chris-greening/spyrograph/blob/main/spyrograph/_trochoid.py#L77) method defined in `_Trochoid` has fairly light documentation. 

It is essentially a wrapper around matplotlib.pyplot.plot as it just passes the kwargs from `plot` down into matplotlib but I feel the current docstring could be improved to provide more context

**Comment by NishanthMuruganantham** [comment]
Hi @chris-greening ,
Hope you're doing well! I am an experienced python developer who is looking to contribute the open source for the first time. 
I found this package interesting and your contribution notes drew my attention as it encourages and welcomes first time contributors.

I am looking to know some insights with respect to this issue like where to get started and what exactly is needed.

Thanks,
Nishanth.

**Comment by chris-greening** [comment]
Heyo @NishanthMuruganantham thanks so much for reaching out!! I love helping new contributors break into open source so always feel free to reach out for questions/advice/etc! 

Let me know if you're interested in having this Issue assigned to you, I'd be more than happy to help walk you through this process

## Background on the project 
The project has an abstract base class at the core named [`_Trochoid`](https://github.com/chris-greening/spyrograph/blob/main/spyrograph/_trochoid.py#L26) that defines a lot of the general behavior in the public user-facing library i.e. the `Hypotrochoid` and `Epitrochoid` classes that inherit from it

Based on the user input arguments `R`, `r`, `d`, `thetas`, etc. these will internally be used to calculate instance attributes `x` and `y` which are arrays of associated coordinates calculated by the [parametric equations](https://github.com/chris-greening/spyrograph/blob/main/spyrograph/hypotrochoid/hypotrochoid.py#L16)

## Background on the `plot` method
The aforementioned `_Trochoid` class has a [`plot`](https://github.com/chris-greening/spyrograph/blob/main/spyrograph/_trochoid.py#L77) method that plots these x and y coordinates using `matplotlib`. I wrote a blog post [here](https://chris-greening.github.io/spyrograph/python,/tutorial/2023/03/27/plotting-beautiful-spirographs-with-matplotlib-and-spyrograph.html) that could serve as a good starting point to understand what the method does with some concrete examples

Since this leverages `matplotlib` under the hood and is essentially just drawing a simple plot I allow the users to pass whatever `matplotlib` [kwargs](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.plot.html) into `_Trochoid.plot` and this then gets passed down into the [internal matplotlib](https://github.com/chris-greening/spyrograph/blob/main/spyrograph/_trochoid.py#L87) call

## What this Issue is asking
For this particular issue I'm looking to give just an improvement to the docstring in this [`plot`](https://github.com/chris-greening/spyrograph/blob/main/spyrograph/_trochoid.py#L77) method. A lot of the public facing methods are [fairly well-documented](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.plot.html) but I find the `plot` docs to be ehhh [kind of lacking](https://spyrograph.readthedocs.io/en/latest/source/spyrograph.hypotrochoid.html#spyrograph.hypotrochoid.Hypotrochoid.plot)

Feel free to sift through the [official docs](https://spyrograph.readthedocs.io/en/latest/index.html) to get an idea of what kind of docs we're trying to build. Still early on in the project so it's a work in progress 😅 

The [`matplotlib.pyplot.plot`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.plot.html) docs actually serve as a pretty good example, essentially just a few paragraphs of what the `plot` method is doing, some examples of how it could be configured via kwargs, maybe some quickstart code snippets i.e. the code snippet from the [blog post](https://chris-greening.github.io/spyrograph/python,/tutorial/2023/03/27/plotting-beautiful-spirographs-with-matplotlib-and-spyrograph.html#plotting-the-hypotrochoid) would be more than sufficient for what we need right now

Nothing set in stone and I'm open to ideas so feel free to submit a draft pull request and we can start spitballing some ideas! Thanks so much for your interest in contributing, like I said lmk and I'll assign this to you!

**Comment by chris-greening** [comment]
Hey @NishanthMuruganantham I just did a project-wide improvement to the docstrings so this one was actually just completed - feel free to jump onto a different issue though I'd love to get you involved! Cheers! :D

**Comment by chris-greening** [comment]
Completed by #102

**Comment by NishanthMuruganantham** [comment]
Thanks for the notification @chris-greening . Apologies for the late response, will try to find some other issues.
