### ISSUE TITLE
Update the `_init_turtles` docstring 

### ISSUE THREAD

**Issue by chris-greening** [chris-greening/spyrograph#72]
**Is your feature request related to a problem? Please describe.**
The implementation details of `_init_turtles` have changed since the last time the docstring was updated - please just add a quick description of the arguments that are getting passed in and the return values.

Since this is a private method we don't have to do a full Return and Parameters section, just a "Returns turtle that does foo, turtle that does bar set with color value, etc."

**Comment by Sjorza** [comment]
This issue is already handled and merged into the main branch. I think this can be closed.

**Comment by chris-greening** [comment]
Thank you for flagging @Sjorza !
