### ISSUE TITLE
Add docstring to `_validate_theta`

### ISSUE THREAD

**Issue by chris-greening** [chris-greening/spyrograph#74]
**Is your feature request related to a problem? Please describe.**
Add a simple docstring to `_validate_theta` that describes its inputs and outputs. This is a private method so we don't need a full documented method, just something quick that explains the inputs and outputs of the function and what it is doing

The purpose of the function is to standardize any potential theta inputs (i.e. a list of thetas or the theta start, stop, step) and A. raise an error if multiple theta definitions are passed and B. return a list of thetas

**Comment by NishanthMuruganantham** [comment]
Hi @chris-greening,
Hope you're doing well. Please let me know whether I can work on this!

Thanks,
Nishant

**Comment by chris-greening** [comment]
Hey @NishanthMuruganantham absolutely!! :D 

The method can be found [here](https://github.com/chris-greening/spyrograph/blob/main/spyrograph/core/_misc.py) - don't hesitate to reach out if you have any questions!

**Comment by NishanthMuruganantham** [comment]
Thanks. I have forked it and will try on this.

**Comment by NishanthMuruganantham** [comment]
@chris-greening  Kindly let me know, whether the docstring should be a simple one liner as it has been described in other functions of the same file or can it be an explanatory one. I am ready for both ways.

**Comment by chris-greening** [comment]
Since this is an internal, private function I think a one liner would be appropriate - just an explanation of what the function returns and a brief summary on what it's checking for

**Comment by NishanthMuruganantham** [comment]
Kindly have a look on this @chris-greening ☺

**Comment by chris-greening** [comment]
Great work my friend! #143 

I'm going to open a bunch more issues similar to this one later today - keep an eye out! :D

**Comment by NishanthMuruganantham** [comment]
I am early looking forward to contribute more and thanks for helping me to kick start this new journey!
