### ISSUE TITLE
Write unit test for the zero or negative ValueError raise

### ISSUE THREAD

**Issue by chris-greening** [chris-greening/spyrograph#95]
**Is your feature request related to a problem? Please describe.**
Write unit tests that ensure a `ValueError` is raised when `Hypotrochoid`, `Epitrochoid`, `Hypocycloid`, or `Epicycloid` are instantiated with a negative or zero value for `R`, `r` or `d`

**Comment by Navinkhandeparkar** [comment]
Hi @chris-greening, can I work on this?

**Comment by chris-greening** [comment]
Heyo @Navinkhandeparkar thanks so much for your interest!! :D

Yes go for it 😎 the tests are in tests/, there is a _TestGeneral class that contains a toplevel test suite that gets inherited by all the aforementioned object's respective tests

You can drop test(s) right in there and they should propagate down
