### ISSUE TITLE
Raise a `ValueError` if empty list of `thetas` is passed to `__init__`

### ISSUE THREAD

**Issue by chris-greening** [chris-greening/spyrograph#99]
**Is your feature request related to a problem? Please describe.**
Currently a user can pass an empty list of `thetas` in to `Hypotrochoid`, `Epitrochoid`, `Epicycloid`, or `Hypocycloid`. This doesn't make contextual sense so we should raise a `ValueError` if an empty list is passed to [_Trochoid.__init__](https://github.com/chris-greening/spyrograph/blob/main/spyrograph/_trochoid.py#L28) (`_Trochoid` is an ABC that defines most of the behavior for the user-facing objects)

There is a [`_Trochoid._validate_thetas`](https://github.com/chris-greening/spyrograph/blob/main/spyrograph/_trochoid.py#L363) private func that is called internally, it would be appropriate to place this in here. 

NOTE: users can also pass `theta_start`, `theta_end`, and `theta_stop` that will build a list of `thetas` similar to `np.arange` - if a user passes `theta_start` == `theta_end` this should raise the same error. Because of this perhaps the "if thetas is empty" check should be at the end of `_validate_thetas`

**Comment by ny248** [comment]
Hi, I am a novice programmer and would like to contribute to your project! May I work on this issue?

**Comment by chris-greening** [comment]
Hello hello @ny248 !!! Welcome to the project - yes absolutely! Let me know if you have any questions at all and I can help walk you through anything you have questions about
